# Generated by Django 5.1.5 on 2025-01-24 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='solo',
            field=models.BooleanField(default=False),
        ),
    ]
